### ISSUE TITLE
Sticky session support missing

### ISSUE THREAD

**Issue by nokjuh** [microsoft/service-fabric-traefik#12]
Load balancer sticky session support is missing, along with related settings which are required for modern browsers. This is present in the Traefik 1.7 plugin. For us this is necessary to be able to use Traefik.

          <Label Key="traefik.http.loadbalancer.stickiness">true</Label>
          <Label Key="traefik.http.loadbalancer.stickiness.secure">true</Label>
          <Label Key="traefik.http.loadbalancer.stickiness.httpOnly">true</Label>
          <Label Key="traefik.http.loadbalancer.stickiness.sameSite">none</Label>
          <Label Key="traefik.http.loadbalancer.stickiness.cookieName">stickycookie</Label>

See below for how this was implemented in the previous repository:
https://github.com/dariopb/traefikServiceFabricPlugin/commit/eed4680f6aeca6a351b514130ff531b8f2b2b382

**Comment by egaribay77** [comment]
Hello, thank you for reaching out. 

This is an issue with documentation.  For load balancer labels need to add ".service." between endPointName and loadbalancer. Also, the current implementation parses the rules differently from the Traefik plugin code. More details here: https://github.com/dariopb/traefikServiceFabricPlugin/issues/10#issuecomment-965612764. The implementation can found in the repo under src/serviceFabricDiscoveryService/pkg/discovery

Example:
```
  <Extensions>
    <Extension Name="Traefik">
        <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
	    <Label Key="traefik.http.WeatherForecastEndpoint0">true</Label>
	    <Label Key="traefik.http.WeatherForecastEndpoint0.router.entrypoints">websecure</Label>
	    <Label Key="traefik.http.WeatherForecast0.router.rule">PathPrefix(`/weatherforecast`)</Label>
	    <Label Key="traefik.http.WeatherForecastEndpoint0.middlewares.1.stripPrefix.prefixes">"/weatherforecast</Label>
            <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.passhostheader">true</Label>
	    <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.healthcheck.path">/weatherforecast</Label>
            <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.healthcheck.interval">10s</Label>
            <Label Key="traefik.http.WeatherForecastrEndpoint0.service.loadbalancer.healthcheck.scheme">https</Label>
            <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.sticky.cookie.name">stickycookie</Label>
            <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.sticky.cookie.secure">true</Label>
            <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.sticky.cookie.httpOnly">true</Label>
            <Label Key="traefik.http.WeatherForecastEndpoint0.service.loadbalancer.sticky.cookie.sameSite">none</Label>
	</Labels>
    </Extension>
  </Extensions>
```



```
Traefik dynamic config file (loadbalancer section):
  services:
    fabric-TestSFApp-WeatherForecastServicePkg-http-WeatherForecastEndpoint0:
      loadBalancer:
        healthCheck:
          followRedirects: null
          interval: 10s
          path: /weatherforecast
          scheme: https
        passHostHeader: true
        servers:
        - Port: ""
          Scheme: ""
          url: http://desktop-xxxxxxxx:8387/
        sticky:
          cookie:
            httpOnly: true
            name: stickycookie
            sameSite: none
            secure: true
```
