### ISSUE TITLE
Fetcher generating duplicate routers & services

### ISSUE THREAD

**Issue by tony-gamble-asos** [microsoft/service-fabric-traefik#5]
The fetcher appears to be generating duplicate routers and services for every router and service defined as part of a single application.

See below example of dynamically generated config whereby routers and service config differs only by name. 

```
http:
  middlewares:
    sf-stripprefixregex_nonpartitioned:
      stripPrefixRegex:
        regex:
        - ^/[^/]*/[^/]*/*
  routers:
    fabric-Application2-Web1-http-defaultEP:
      entryPoints:
      - websecure
      middlewares:
      - sf-stripprefixregex_nonpartitioned
      rule: PathPrefix(`/WeatherForecast`)
      service: fabric-Application2-Web1-http-defaultEP
      tls:
        options: "false"
    fabric-Application2-Web1-http-defaultEP-861ef74e-6895-4f76-b4d0-d257f48a923d:
      entryPoints:
      - websecure
      middlewares:
      - sf-stripprefixregex_nonpartitioned
      rule: PathPrefix(`/WeatherForecast`)
      service: fabric-Application2-Web1-http-defaultEP-861ef74e-6895-4f76-b4d0-d257f48a923d
      tls:
        options: "false"
  services:
    fabric-Application2-Web1-http-defaultEP:
      loadBalancer:
        healthCheck:
          followRedirects: null
          interval: 10s
          path: /healthcheck
          scheme: http
        passHostHeader: true
        servers:
        - Port: ""
          Scheme: ""
          url: http://machinename:8311
    fabric-Application2-Web1-http-defaultEP-861ef74e-6895-4f76-b4d0-d257f48a923d:
      loadBalancer:
        healthCheck:
          followRedirects: null
          interval: 10s
          path: /healthcheck
          scheme: http
        passHostHeader: true
        servers:
        - Port: ""
          Scheme: ""
          url: http://machinename:8311
```

ServiceManifest labels defined :

```
<ServiceTypes>
    <!-- This is the name of your ServiceType. 
         This name must match the string used in RegisterServiceType call in Program.cs. -->
    <StatelessServiceType ServiceTypeName="Web1Type" >
      <Extensions>
        <Extension Name="traefik">
          <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
            <Label Key="traefik.http.defaultEP">true</Label>
            <Label Key="traefik.http.defaultEP.router.entryPoints">websecure</Label>
            <Label Key="traefik.http.defaultEP.router.rule">PathPrefix(`/WeatherForecast`)</Label>
            <Label Key="traefik.http.defaultEP.router.tls.options">false</Label>
            <Label Key="traefik.http.defaultEP.service.loadbalancer.passhostheader">true</Label>
            <Label Key="traefik.http.defaultEP.service.loadbalancer.healthcheck.path">/healthcheck</Label>
            <Label Key="traefik.http.defaultEP.service.loadbalancer.healthcheck.interval">10s</Label>
            <Label Key="traefik.http.defaultEP.service.loadbalancer.healthcheck.scheme">http</Label>
          </Labels>
        </Extension>
      </Extensions>
    </StatelessServiceType>
  </ServiceTypes>
```

Is this by design?
